# Generated by Django 5.2.1 on 2025-05-27 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("EUR", "€ Euro"),
                            ("USD", "$ Dólar"),
                            ("BTC", "₿ Bitcoin"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CuentaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("entidad", models.CharField(blank=True, max_length=100)),
                ("activa", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ticker", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACCION", "Acción"),
                            ("CRIPTO", "Criptomoneda"),
                            ("FONDO", "Fondo"),
                            ("ETF", "ETF"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("moneda", models.CharField(default="EUR", max_length=10)),
                ("plataforma", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cantidad_actual",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Cantidad actual de activos",
                        max_digits=20,
                    ),
                ),
                (
                    "actualizable",
                    models.BooleanField(
                        default=True,
                        help_text="Si está marcado, se actualizará el valor automáticamente vía API",
                    ),
                ),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoInversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra"),
                            ("VENTA", "Venta"),
                            ("DIVIDENDO", "Dividendo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "comision",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "inversion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="finanzas.inversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "total_inversiones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_vehiculos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_hipotecas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_creditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_prestamos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "anio", "mes")},
            },
        ),
        migrations.CreateModel(
            name="PrestamoSimple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("entidad", models.CharField(blank=True, max_length=100)),
                (
                    "total_pendiente",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.registromensual",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeudaMensualCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deuda", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.cuentacredito",
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.registromensual",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TarjetaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("entidad", models.CharField(blank=True, max_length=100)),
                ("activa", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValorActualInversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fuente", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "inversion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valor_actual",
                        to="finanzas.inversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialValorInversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "cantidad_activos",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Cantidad de activos en esa fecha",
                        max_digits=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("fuente", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "inversion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_valores",
                        to="finanzas.inversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("inversion", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="ResumenInversionesMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_valor", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "total_aportado",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "total_rentabilidad",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "variacion_mensual",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.registromensual",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "registro")},
            },
        ),
        migrations.CreateModel(
            name="SaldoMensualCuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.cuentabancaria",
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.registromensual",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cuenta", "registro"),
                        name="unique_saldo_por_cuenta_y_registro",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SaldoMensualTarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.registromensual",
                    ),
                ),
                (
                    "tarjeta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.tarjetacredito",
                    ),
                ),
            ],
            options={
                "unique_together": {("tarjeta", "registro")},
            },
        ),
    ]
