# Generated by Django 5.2.1 on 2026-05-30 10:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_userprofile_rol_hogar_userprofile_hogar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CotizacionSS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        choices=[("ES", "España")], default="ES", max_length=5
                    ),
                ),
                (
                    "concepto",
                    models.CharField(
                        help_text="Ej: Contingencias comunes, Desempleo, Formación...",
                        max_length=100,
                    ),
                ),
                (
                    "porcentaje_trabajador",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("año", models.IntegerField()),
            ],
            options={
                "ordering": ["pais", "año", "concepto"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fijo", "Gasto Fijo"),
                            ("anual", "Gasto Anual (provision)"),
                            ("variable", "Gasto Variable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("es_predefinida", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_gasto",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "nombre"],
                "unique_together": {("hogar", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("EUR", "€ Euro"),
                            ("USD", "$ Dólar"),
                            ("BTC", "₿ Bitcoin"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CuentaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("entidad", models.CharField(blank=True, max_length=100)),
                ("activa", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DestinoIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("es_predefinido", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinos_ingreso",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "unique_together": {("hogar", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="FondoFamiliar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Fondo comun, Ahorro piso, Inversion, Emergencia...",
                        max_length=100,
                    ),
                ),
                (
                    "tipo_fondo",
                    models.CharField(
                        choices=[
                            ("comun", "Fondo común del hogar"),
                            ("ahorro", "Ahorro"),
                            ("inversion", "Inversión"),
                        ],
                        default="comun",
                        help_text="Categoría del fondo para reporting (ahorro, inversión, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "modo_aportacion",
                    models.CharField(
                        choices=[
                            ("igual", "A partes iguales"),
                            ("proporcional", "Proporcional al ingreso"),
                            ("fijo", "Importe fijo por persona"),
                        ],
                        default="proporcional",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="#a259ff", max_length=7)),
                (
                    "cuenta_asociada",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre o descripcion de la cuenta bancaria asociada a este fondo. Ej: Revolut conjunta, BBVA ahorro...",
                        max_length=150,
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fondos",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "nombre"],
                "unique_together": {("hogar", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="FuenteIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Schneider Electric, Guardias hospital, Alquiler piso...",
                        max_length=150,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("fijo", "Fijo"), ("variable", "Variable estimado")],
                        default="fijo",
                        max_length=20,
                    ),
                ),
                (
                    "modo_entrada",
                    models.CharField(
                        choices=[
                            ("anual", "Declaro el total anual"),
                            ("periodo", "Declaro por periodo"),
                        ],
                        default="anual",
                        max_length=10,
                    ),
                ),
                (
                    "importe_declarado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importe tal como lo introduce el usuario (anual o por periodo)",
                        max_digits=12,
                    ),
                ),
                ("es_bruto", models.BooleanField(default=True)),
                (
                    "pais_fiscal",
                    models.CharField(
                        choices=[
                            ("ES", "España"),
                            ("US", "Estados Unidos"),
                            ("UK", "Reino Unido"),
                            ("FR", "Francia"),
                            ("DE", "Alemania"),
                            ("PT", "Portugal"),
                            ("IT", "Italia"),
                            ("MX", "México"),
                            ("CO", "Colombia"),
                            ("AR", "Argentina"),
                        ],
                        default="ES",
                        max_length=5,
                    ),
                ),
                (
                    "num_pagas",
                    models.IntegerField(
                        default=12, help_text="Reparto del anual en pagas."
                    ),
                ),
                (
                    "meses_pagas_extras",
                    models.CharField(
                        blank=True,
                        default="6,12",
                        help_text="Meses de pagas extras separados por coma. Ej: 6,12 para junio y diciembre",
                        max_length=50,
                    ),
                ),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("diaria", "Diaria"),
                            ("semanal", "Semanal"),
                            ("mensual", "Mensual"),
                            ("trimestral", "Trimestral"),
                            ("semestral", "Semestral"),
                            ("anual", "Anual"),
                            ("puntual", "Puntual"),
                        ],
                        default="mensual",
                        max_length=20,
                    ),
                ),
                (
                    "meses_cobro",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Meses de cobro separados por coma. Ej: 3,6,9,12 para trimestral",
                        max_length=50,
                    ),
                ),
                (
                    "porcentaje_variabilidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="% de variabilidad. Ej: 40 = +40% sobre la base.",
                        max_digits=5,
                    ),
                ),
                (
                    "incluir_en_mensual",
                    models.BooleanField(
                        default=True,
                        help_text="Si False, solo aparece en el ponderado, no en el mensual base.",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "destino",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destino para ingresos no recurrentes mensuales.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuentes",
                        to="finanzas.destinoingreso",
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuentes_ingreso",
                        to="core.hogar",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuentes_ingreso",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["usuario", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="IngresoExtraordinario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concepto",
                    models.CharField(
                        help_text="Ej: Bonus anual, Devolución IRPF, Venta coche...",
                        max_length=200,
                    ),
                ),
                ("importe", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "es_neto",
                    models.BooleanField(
                        default=True,
                        help_text="True = ya neto, False = bruto (se aplicarán retenciones)",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField(help_text="Mes en que se recibe (1-12)")),
                ("nota", models.CharField(blank=True, default="", max_length=255)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fondo_destino",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si se asigna, este ingreso alimenta directamente el fondo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingresos_extraordinarios",
                        to="finanzas.fondofamiliar",
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingresos_extraordinarios",
                        to="core.hogar",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingresos_extraordinarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-año", "-mes", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Inversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ticker", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACCION", "Acción"),
                            ("CRIPTO", "Criptomoneda"),
                            ("FONDO", "Fondo"),
                            ("ETF", "ETF"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("moneda", models.CharField(default="EUR", max_length=10)),
                ("plataforma", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cantidad_actual",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Cantidad actual de activos",
                        max_digits=20,
                    ),
                ),
                (
                    "actualizable",
                    models.BooleanField(
                        default=True,
                        help_text="Si está marcado, se actualizará el valor automáticamente vía API",
                    ),
                ),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoInversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra"),
                            ("VENTA", "Venta"),
                            ("DIVIDENDO", "Dividendo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "comision",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "inversion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="finanzas.inversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartidaGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importe por periodo declarado",
                        max_digits=12,
                    ),
                ),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("mensual", "Mensual"),
                            ("bimensual", "Bimensual"),
                            ("trimestral", "Trimestral"),
                            ("semestral", "Semestral"),
                            ("anual", "Anual"),
                        ],
                        default="mensual",
                        help_text="Cada cuanto se paga este gasto",
                        max_length=20,
                    ),
                ),
                (
                    "mes_pago",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ],
                        help_text="Para gastos no mensuales: mes principal de pago.",
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas",
                        to="finanzas.categoriagasto",
                    ),
                ),
                (
                    "fondo_asignado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fondo común que cubre este gasto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gastos_asignados",
                        to="finanzas.fondofamiliar",
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas_gasto",
                        to="core.hogar",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si vacio, es un gasto compartido del hogar.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gastos_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="RegistroMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "total_inversiones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_vehiculos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_hipotecas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_creditos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_prestamos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "anio", "mes")},
            },
        ),
        migrations.CreateModel(
            name="PrestamoSimple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("entidad", models.CharField(blank=True, max_length=100)),
                (
                    "total_pendiente",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.registromensual",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeudaMensualCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deuda", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.cuentacredito",
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.registromensual",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReglaReparto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo_regla",
                    models.CharField(
                        choices=[
                            ("porcentaje", "Porcentaje del dinero libre"),
                            ("fijo", "Importe fijo mensual"),
                        ],
                        default="porcentaje",
                        max_length=20,
                    ),
                ),
                (
                    "periodicidad_regla",
                    models.CharField(
                        choices=[
                            ("mensual", "Aplica cada mes sobre ingreso mensual"),
                            ("anual", "Aplica sobre ingresos anuales / pagas extras"),
                        ],
                        default="mensual",
                        help_text="Mensual: opera sobre el libre mensual. Anual: opera sobre pagas extras e ingresos extraordinarios del mes.",
                        max_length=10,
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Porcentaje del dinero libre (solo si tipo=porcentaje)",
                        max_digits=5,
                    ),
                ),
                (
                    "importe_fijo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Importe fijo mensual (solo si tipo=fijo)",
                        max_digits=12,
                    ),
                ),
                ("color", models.CharField(default="#a259ff", max_length=7)),
                ("orden", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fondo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fondo al que se destina. Si vacio, es dinero sin asignar a fondo.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas",
                        to="finanzas.fondofamiliar",
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_reparto",
                        to="core.hogar",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si se especifica, esta regla aplica solo a este miembro. Si vacio, aplica al total del hogar.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reglas_reparto",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="SubsobreFondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Ocio, Restaurantes, Alimentación, Ropa, Suscripciones...",
                        max_length=100,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("gasto_fijo", "Cubre gasto fijo del hogar"),
                            ("gasto_variable", "Cubre gasto variable del hogar"),
                            ("discrecional", "Gasto discrecional"),
                            ("libre", "Sin asignación / libre"),
                        ],
                        default="discrecional",
                        max_length=20,
                    ),
                ),
                (
                    "importe_manual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Importe mensual fijo si no hay partidas vinculadas.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fondo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsobres",
                        to="finanzas.fondofamiliar",
                    ),
                ),
                (
                    "fondo_destino",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si se indica, el importe de este sobre se transfiere a otro fondo (ej: del Fondo Común → Ahorro Piso). Mutuamente excluyente con partidas.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subsobres_entrantes",
                        to="finanzas.fondofamiliar",
                    ),
                ),
                (
                    "partidas_vinculadas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Si vinculas partidas, el importe se calcula sumando su importe_mensual.",
                        to="finanzas.partidagasto",
                    ),
                ),
            ],
            options={
                "ordering": ["fondo", "orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="TablaIRPF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        choices=[
                            ("ES", "España"),
                            ("US", "Estados Unidos"),
                            ("UK", "Reino Unido"),
                            ("FR", "Francia"),
                            ("DE", "Alemania"),
                            ("PT", "Portugal"),
                            ("IT", "Italia"),
                            ("MX", "México"),
                            ("CO", "Colombia"),
                            ("AR", "Argentina"),
                        ],
                        default="ES",
                        max_length=5,
                    ),
                ),
                ("tramo_desde", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tramo_hasta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dejar vacío para el último tramo (sin límite)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tipo impositivo del tramo en %",
                        max_digits=5,
                    ),
                ),
                ("año", models.IntegerField(help_text="Año fiscal de aplicación")),
            ],
            options={
                "ordering": ["pais", "año", "tramo_desde"],
                "unique_together": {("pais", "año", "tramo_desde")},
            },
        ),
        migrations.CreateModel(
            name="TarjetaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("entidad", models.CharField(blank=True, max_length=100)),
                ("activa", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValorActualInversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fuente", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "inversion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valor_actual",
                        to="finanzas.inversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AjusteIngresoMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField(help_text="Número de mes 1-12")),
                (
                    "importe_real",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importe neto real cobrado este mes (ya neto, sin recalcular IRPF)",
                        max_digits=12,
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ej: 'Solo 3 guardias este mes'",
                        max_length=255,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fuente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustes_mensuales",
                        to="finanzas.fuenteingreso",
                    ),
                ),
            ],
            options={
                "ordering": ["-año", "-mes"],
                "unique_together": {("fuente", "año", "mes")},
            },
        ),
        migrations.CreateModel(
            name="HistorialValorInversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "cantidad_activos",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Cantidad de activos en esa fecha",
                        max_digits=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("fuente", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "inversion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_valores",
                        to="finanzas.inversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("inversion", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="ResumenInversionesMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_valor", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "total_aportado",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "total_rentabilidad",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "variacion_mensual",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.registromensual",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "registro")},
            },
        ),
        migrations.CreateModel(
            name="SaldoMensualCuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.cuentabancaria",
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.registromensual",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cuenta", "registro"),
                        name="unique_saldo_por_cuenta_y_registro",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SaldoMensualTarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.registromensual",
                    ),
                ),
                (
                    "tarjeta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.tarjetacredito",
                    ),
                ),
            ],
            options={
                "unique_together": {("tarjeta", "registro")},
            },
        ),
    ]
