# Generated by Django 5.2.1 on 2025-05-20 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaldoMensualTarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="TarjetaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("entidad", models.CharField(blank=True, max_length=100)),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="registromensual",
            name="fecha_creacion",
        ),
        migrations.AddField(
            model_name="registromensual",
            name="total_creditos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="registromensual",
            name="total_prestamos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="cuentabancaria",
            name="moneda",
            field=models.CharField(
                choices=[("EUR", "€ Euro"), ("USD", "$ Dólar"), ("BTC", "₿ Bitcoin")],
                default="EUR",
                max_length=3,
            ),
        ),
        migrations.AddConstraint(
            model_name="saldomensualcuenta",
            constraint=models.UniqueConstraint(
                fields=("cuenta", "registro"), name="unique_saldo_por_cuenta_y_registro"
            ),
        ),
        migrations.AddField(
            model_name="saldomensualtarjeta",
            name="registro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finanzas.registromensual",
            ),
        ),
        migrations.AddField(
            model_name="tarjetacredito",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="saldomensualtarjeta",
            name="tarjeta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finanzas.tarjetacredito",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saldomensualtarjeta",
            unique_together={("tarjeta", "registro")},
        ),
    ]
