# Generated by Django 6.0.5 on 2026-05-21 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_rol_hogar_userprofile_hogar'),
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('ES', 'España')], default='ES', max_length=5)),
                ('concepto', models.CharField(help_text='Ej: Contingencias comunes, Desempleo, Formación...', max_length=100)),
                ('porcentaje_trabajador', models.DecimalField(decimal_places=2, max_digits=5)),
                ('año', models.IntegerField()),
            ],
            options={
                'ordering': ['pais', 'año', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='DestinoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('es_predefinido', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos_ingreso', to='core.hogar')),
            ],
            options={
                'unique_together': {('hogar', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='FuenteIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Schneider Electric, Ventas de pan, Alquiler piso...', max_length=150)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe por periodo', max_digits=12)),
                ('es_bruto', models.BooleanField(default=True, help_text='Si es bruto, se calcularán retenciones automáticamente')),
                ('pais_fiscal', models.CharField(choices=[('ES', 'España'), ('US', 'Estados Unidos'), ('UK', 'Reino Unido'), ('FR', 'Francia'), ('DE', 'Alemania'), ('PT', 'Portugal'), ('IT', 'Italia'), ('MX', 'México'), ('CO', 'Colombia'), ('AR', 'Argentina')], default='ES', max_length=5)),
                ('periodicidad', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('puntual', 'Puntual')], default='mensual', max_length=20)),
                ('mes_cobro', models.IntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], help_text='Mes en que se cobra. Solo para ingresos no mensuales.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(blank=True, help_text='Solo para ingresos no mensuales: a dónde va este dinero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuentes', to='finanzas.destinoingreso')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_ingreso', to='core.hogar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_ingreso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario', '-periodicidad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TablaIRPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('ES', 'España'), ('US', 'Estados Unidos'), ('UK', 'Reino Unido'), ('FR', 'Francia'), ('DE', 'Alemania'), ('PT', 'Portugal'), ('IT', 'Italia'), ('MX', 'México'), ('CO', 'Colombia'), ('AR', 'Argentina')], default='ES', max_length=5)),
                ('tramo_desde', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tramo_hasta', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar vacío para el último tramo (sin límite)', max_digits=12, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Tipo impositivo del tramo en %', max_digits=5)),
                ('año', models.IntegerField(help_text='Año fiscal de aplicación')),
            ],
            options={
                'ordering': ['pais', 'año', 'tramo_desde'],
                'unique_together': {('pais', 'año', 'tramo_desde')},
            },
        ),
    ]
