# Generated by Django 5.2.1 on 2026-05-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reglareparto",
            name="solo_mes",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Enero"),
                    (2, "Febrero"),
                    (3, "Marzo"),
                    (4, "Abril"),
                    (5, "Mayo"),
                    (6, "Junio"),
                    (7, "Julio"),
                    (8, "Agosto"),
                    (9, "Septiembre"),
                    (10, "Octubre"),
                    (11, "Noviembre"),
                    (12, "Diciembre"),
                ],
                help_text="Si se especifica, esta regla SOLO se aplica en ese mes. Vacio = todos los meses.",
                null=True,
            ),
        ),
    ]
