# Generated by Django 6.0.5 on 2026-05-22 09:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_cotizacionss_destinoingreso_fuenteingreso_tablairpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuenteingreso',
            options={'ordering': ['usuario', 'nombre']},
        ),
        migrations.AddField(
            model_name='fuenteingreso',
            name='incluir_en_mensual',
            field=models.BooleanField(default=True, help_text='Si False, solo aparece en el ponderado anual, no en el mensual base.'),
        ),
        migrations.AddField(
            model_name='fuenteingreso',
            name='num_pagas',
            field=models.IntegerField(default=12, help_text='Número de pagas al año. Ej: 14 para salarios con extras en junio y diciembre.'),
        ),
        migrations.AddField(
            model_name='fuenteingreso',
            name='porcentaje_variabilidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='% de variabilidad sobre el importe base. Ej: 40 = ±40%. Solo para tipo variable o mixto.', max_digits=5),
        ),
        migrations.AddField(
            model_name='fuenteingreso',
            name='tipo',
            field=models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable estimado'), ('mixto', 'Mixto (base + variable)')], default='fijo', max_length=20),
        ),
        migrations.AlterField(
            model_name='fuenteingreso',
            name='destino',
            field=models.ForeignKey(blank=True, help_text='Destino para ingresos no recurrentes mensuales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuentes', to='finanzas.destinoingreso'),
        ),
        migrations.AlterField(
            model_name='fuenteingreso',
            name='es_bruto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fuenteingreso',
            name='importe',
            field=models.DecimalField(decimal_places=2, help_text='Importe por periodo declarado', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fuenteingreso',
            name='mes_cobro',
            field=models.IntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], help_text='Mes de cobro para ingresos no mensuales.', null=True),
        ),
        migrations.AlterField(
            model_name='fuenteingreso',
            name='nombre',
            field=models.CharField(help_text='Ej: Schneider Electric, Guardias hospital, Alquiler piso...', max_length=150),
        ),
    ]
