# Generated by Django 5.2.1 on 2026-05-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_rol_hogar_userprofile_hogar"),
        ("finanzas", "0002_solo_mes_reglareparto"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngresoRealMes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("importe", models.DecimalField(decimal_places=2, max_digits=12)),
                ("nota", models.CharField(blank=True, default="", max_length=255)),
                ("registrado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingresos_reales",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "ordering": ["-año", "-mes"],
                "unique_together": {("hogar", "año", "mes")},
            },
        ),
        migrations.CreateModel(
            name="SaldoRealFondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField(help_text="1-12")),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=14)),
                ("nota", models.CharField(blank=True, default="", max_length=255)),
                ("registrado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fondo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saldos_reales",
                        to="finanzas.fondofamiliar",
                    ),
                ),
            ],
            options={
                "ordering": ["-año", "-mes", "fondo"],
                "unique_together": {("fondo", "año", "mes")},
            },
        ),
    ]
