# Generated by Django 6.0.5 on 2026-05-22 09:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_fuenteingreso_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuenteingreso',
            name='importe',
        ),
        migrations.RemoveField(
            model_name='fuenteingreso',
            name='mes_cobro',
        ),
        migrations.AddField(
            model_name='fuenteingreso',
            name='importe_declarado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importe tal como lo introduce el usuario (anual o por periodo)', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuenteingreso',
            name='meses_cobro',
            field=models.CharField(blank=True, default='', help_text='Meses de cobro separados por coma. Ej: 3,6,9,12 para trimestral', max_length=50),
        ),
        migrations.AddField(
            model_name='fuenteingreso',
            name='meses_pagas_extras',
            field=models.CharField(blank=True, default='6,12', help_text='Meses de pagas extras separados por coma. Ej: 6,12 para junio y diciembre', max_length=50),
        ),
        migrations.AddField(
            model_name='fuenteingreso',
            name='modo_entrada',
            field=models.CharField(choices=[('anual', 'Declaro el total anual'), ('periodo', 'Declaro por periodo')], default='anual', max_length=10),
        ),
        migrations.AlterField(
            model_name='fuenteingreso',
            name='incluir_en_mensual',
            field=models.BooleanField(default=True, help_text='Si False, solo aparece en el ponderado, no en el mensual base.'),
        ),
        migrations.AlterField(
            model_name='fuenteingreso',
            name='num_pagas',
            field=models.IntegerField(default=12, help_text='Reparto del anual en pagas.'),
        ),
        migrations.AlterField(
            model_name='fuenteingreso',
            name='porcentaje_variabilidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='% de variabilidad. Ej: 40 = +40% sobre la base.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fuenteingreso',
            name='tipo',
            field=models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable estimado')], default='fijo', max_length=20),
        ),
    ]
