# Generated by Django 5.2.1 on 2026-06-09 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_subsobrefondo_solo_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='fondo',
            field=models.ForeignKey(blank=True, help_text='Fondo de inversión al que pertenece este activo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inversiones', to='finanzas.fondofamiliar'),
        ),
    ]
