# Generated by Django 5.2.1 on 2026-06-23 18:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_rol_hogar_userprofile_hogar"),
        ("finanzas", "0005_tickercatalogo_inversion_fondo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Propiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Piso calle Mayor, Local Getafe…", max_length=200
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vivienda", "Vivienda"),
                            ("local", "Local comercial"),
                            ("terreno", "Terreno"),
                            ("garaje", "Garaje / Plaza"),
                            ("otro", "Otro inmueble"),
                        ],
                        default="vivienda",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=500)),
                ("fecha_compra", models.DateField()),
                (
                    "precio_compra",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio escriturado (sin gastos de compra)",
                        max_digits=12,
                    ),
                ),
                (
                    "gastos_compra",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="ITP/AJD, notaría, registro, gestoría…",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_actual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valoración actual de mercado",
                        max_digits=12,
                    ),
                ),
                (
                    "deuda_hipotecaria",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Capital pendiente de hipoteca a día de hoy",
                        max_digits=12,
                    ),
                ),
                (
                    "gastos_venta_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("6.0"),
                        help_text="% costes de venta: agencia (~3%), notaría+gestoría (~1%), etc.",
                        max_digits=5,
                    ),
                ),
                (
                    "es_residencia_habitual",
                    models.BooleanField(
                        default=False,
                        help_text="Puede influir en exenciones fiscales al vender",
                    ),
                ),
                ("color", models.CharField(default="#e67e22", max_length=7)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propiedades",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistorialPropiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField(help_text="1-12")),
                ("valor_mercado", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deuda_hipotecaria",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("nota", models.CharField(blank=True, default="", max_length=255)),
                ("registrado_en", models.DateTimeField(auto_now=True)),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="finanzas.propiedad",
                    ),
                ),
            ],
            options={
                "ordering": ["-año", "-mes"],
                "unique_together": {("propiedad", "año", "mes")},
            },
        ),
    ]
