# Generated by Django 5.2.1 on 2026-06-09 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_inversion_fondo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('exchange', models.CharField(blank=True, default='', max_length=50)),
                ('tipo_activo', models.CharField(blank=True, default='', help_text='EQUITY, ETF, CRYPTOCURRENCY, MUTUALFUND...', max_length=30)),
                ('moneda', models.CharField(blank=True, default='', max_length=10)),
                ('buscado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.AlterField(
            model_name='fondofamiliar',
            name='cuenta_asociada',
            field=models.CharField(blank=True, default='', help_text='Nombre o descripcion de la cuenta bancaria asociada a este fondo.', max_length=150),
        ),
        migrations.AlterField(
            model_name='subsobrefondo',
            name='fondo_destino',
            field=models.ForeignKey(blank=True, help_text='Si se indica, el importe de este sobre se transfiere a otro fondo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsobres_entrantes', to='finanzas.fondofamiliar'),
        ),
    ]
