# Generated by Django 5.2.1 on 2026-06-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_tickercatalogo_inversion_fondo_and_more'),
        ('finanzas', '0006_tickercatalogo_alter_fondofamiliar_cuenta_asociada_and_more'),
    ]

    operations = [
    ]
