# Generated by Django 5.2.1 on 2026-08-03 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0008_merge_propiedad_historialpropiedad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoInversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("color", models.CharField(default="#2d6a4f", max_length=7)),
                ("orden", models.IntegerField(default=0)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carteras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "nombre"],
                "unique_together": {("usuario", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="inversion",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                help_text="Cartera de inversión a la que pertenece este activo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inversiones",
                to="finanzas.grupoinversion",
            ),
        ),
    ]
