# Generated by Django 5.2.1 on 2026-08-03 09:45

import django.db.models.deletion
from django.db import migrations, models


def cascada_grupo_a_compras(apps, schema_editor):
    """La cartera pasa a ser a nivel de compra. Para no perder las carteras ya
    asignadas a nivel de activo (iteración anterior), propagamos Inversion.grupo
    a todas las compras (COMPRA) de ese activo."""
    Inversion = apps.get_model("finanzas", "Inversion")
    MovimientoInversion = apps.get_model("finanzas", "MovimientoInversion")
    for inv in Inversion.objects.filter(grupo__isnull=False):
        MovimientoInversion.objects.filter(
            inversion=inv, tipo="COMPRA", grupo__isnull=True
        ).update(grupo_id=inv.grupo_id)


def revertir(apps, schema_editor):
    # No-op: al revertir se elimina la columna de todos modos.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0009_grupoinversion_inversion_grupo"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinversion",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                help_text="Cartera de inversión a la que pertenece esta compra.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_compra",
                to="finanzas.grupoinversion",
            ),
        ),
        migrations.RunPython(cascada_grupo_a_compras, revertir),
    ]
