# Generated by Django 5.2.1 on 2026-08-04 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0010_movimientoinversion_grupo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inversion",
            name="excluir_de_patrimonio",
            field=models.BooleanField(
                default=False,
                help_text="No sumar en los totales de cartera ni en el patrimonio de los simuladores (p. ej. depósitos que ya cuentas en otra parte de la app). Sigue apareciendo en Inversiones, en su propia sección, y en el Informe Hacienda.",
            ),
        ),
        migrations.AlterField(
            model_name="inversion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ACCION", "Acción"),
                    ("CRIPTO", "Criptomoneda"),
                    ("FONDO", "Fondo"),
                    ("ETF", "ETF"),
                    ("DEPOSITO", "Depósito"),
                    ("OTRO", "Otro"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AportacionRecurrente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("importe", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "dia_mes",
                    models.IntegerField(
                        default=1,
                        help_text="Día del mes de la aportación (1-28, para que exista en todos los meses).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(help_text="Mes de la primera aportación."),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Último mes de aportación. Vacío = sigue indefinidamente (hasta hoy).",
                        null=True,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                (
                    "inversion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aportaciones_recurrentes",
                        to="finanzas.inversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-activa", "-fecha_inicio"],
            },
        ),
        migrations.AddField(
            model_name="movimientoinversion",
            name="origen_recurrente",
            field=models.ForeignKey(
                blank=True,
                help_text="Regla de aportación recurrente que generó este movimiento (si aplica).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_generados",
                to="finanzas.aportacionrecurrente",
            ),
        ),
    ]
