# Generated by Django 5.2.1 on 2026-08-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finanzas",
            "0011_inversion_excluir_de_patrimonio_alter_inversion_tipo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inversion",
            name="deposito_fecha_liquidacion",
            field=models.DateField(
                blank=True,
                help_text="Fecha de liquidación/vencimiento. Si se indica, el valor y el interés se calculan hasta esa fecha (deja de acumular después).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inversion",
            name="deposito_frecuencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diaria", "Diaria"),
                    ("mensual", "Mensual"),
                    ("trimestral", "Trimestral"),
                    ("semestral", "Semestral"),
                    ("anual", "Anual"),
                ],
                default="anual",
                help_text="Cada cuánto capitaliza (paga) el interés el depósito.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="inversion",
            name="deposito_tipo_interes",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Tipo de interés NOMINAL anual del depósito (%). Solo para depósitos.",
                max_digits=6,
                null=True,
            ),
        ),
    ]
