# Generated by Django 5.2.1 on 2026-08-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0012_inversion_deposito_fecha_liquidacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inversion",
            name="excluir_de_patrimonio",
        ),
        migrations.AddField(
            model_name="inversion",
            name="deposito_saldo_fecha",
            field=models.DateField(
                blank=True,
                help_text="Fecha a la que corresponde el saldo real indicado.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inversion",
            name="deposito_saldo_manual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Saldo REAL de hoy del depósito. Si se indica, el valor actual y el interés generado se calculan a partir de este saldo (en vez del interés teórico), para cuadrar con lo que dice el banco.",
                max_digits=14,
                null=True,
            ),
        ),
    ]
