# Generated by Django 5.2.1 on 2026-08-04 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0013_remove_inversion_excluir_de_patrimonio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fondofamiliar",
            name="propietario",
            field=models.ForeignKey(
                blank=True,
                help_text="Titular del fondo. Determina quién declara sus rendimientos en el Informe Hacienda. Vacío = compartido del hogar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fondos_propios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
