# Generated by Django 5.2.1 on 2026-08-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0014_fondofamiliar_propietario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriagasto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("fijo", "Gasto Fijo"),
                    ("anual", "Gasto Anual (provision)"),
                    ("variable", "Gasto Variable"),
                    ("discrecional", "Gasto Discrecional"),
                    ("ingreso", "Ingreso"),
                    ("traspaso", "Traspaso entre cuentas"),
                ],
                max_length=20,
            ),
        ),
    ]
