# Generated by Django 5.2.1 on 2026-09-05 08:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile_tema"),
        ("finanzas", "0016_recolocar_categorias"),
    ]

    operations = [
        migrations.CreateModel(
            name="CierreMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField(help_text="Número de mes 1-12")),
                (
                    "ingreso",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Ingreso neto del hogar ese mes, tal y como quedó al cerrarlo.",
                        max_digits=12,
                    ),
                ),
                (
                    "gastos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total de gastos del mes al cerrarlo.",
                        max_digits=12,
                    ),
                ),
                (
                    "inversion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Importe que ese mes salió hacia fondos de inversión.",
                        max_digits=12,
                    ),
                ),
                ("congelado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cierres_mensuales",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre mensual",
                "verbose_name_plural": "Cierres mensuales",
                "ordering": ["-año", "-mes"],
                "unique_together": {("hogar", "año", "mes")},
            },
        ),
    ]
