# Generated by Django 5.2.1 on 2026-08-05 23:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_rol_hogar_userprofile_hogar"),
        ("finanzas", "0016_recolocar_categorias"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulacionVivienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modo",
                    models.CharField(
                        choices=[
                            ("maximo", "¿Cuánto me puedo permitir?"),
                            ("precio", "Simular un precio concreto"),
                        ],
                        default="maximo",
                        max_length=10,
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("300000"), max_digits=12
                    ),
                ),
                (
                    "entrada_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20"), max_digits=5
                    ),
                ),
                (
                    "tipo_interes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.00"), max_digits=5
                    ),
                ),
                ("plazo_anios", models.PositiveIntegerField(default=25)),
                (
                    "gastos_compra_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("11"), max_digits=5
                    ),
                ),
                (
                    "meses_colchon",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Meses de gastos que quieres conservar sin tocar.",
                    ),
                ),
                (
                    "max_esfuerzo_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30"),
                        help_text="Porcentaje máximo de la base que quieres dedicar a la cuota.",
                        max_digits=5,
                    ),
                ),
                (
                    "base_esfuerzo",
                    models.CharField(
                        choices=[
                            ("ingresos", "Ingresos netos"),
                            ("libre", "Dinero libre mensual"),
                        ],
                        default="ingresos",
                        max_length=10,
                    ),
                ),
                (
                    "ibi_pct_anual",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.500"),
                        help_text="IBI anual como % del precio de la vivienda.",
                        max_digits=5,
                    ),
                ),
                (
                    "comunidad_mes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("60"), max_digits=8
                    ),
                ),
                (
                    "seguro_hogar_anio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("300"), max_digits=8
                    ),
                ),
                (
                    "mantenimiento_pct_anual",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        help_text="Provisión anual de mantenimiento como % del precio.",
                        max_digits=5,
                    ),
                ),
                (
                    "sustituye_vivienda_actual",
                    models.BooleanField(
                        default=False,
                        help_text="Si al comprar dejas de pagar el alquiler o la hipoteca actual.",
                    ),
                ),
                (
                    "propiedades_vendidas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs de propiedades cuya venta financia la compra.",
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "hogar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulacion_vivienda",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulación de vivienda",
                "verbose_name_plural": "Simulaciones de vivienda",
            },
        ),
    ]
