# Generated by Django 5.2.1 on 2026-09-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0017_cierremensual"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuenteingreso",
            name="incluir_en_distribucion",
            field=models.BooleanField(
                default=True,
                help_text="Si se desmarca, el ingreso sigue declarado (cuenta para el total anual y para el IRPF) pero NO entra en el reparto mensual del hogar: ni en el dinero a distribuir, ni en la proporción con la que se cubren los gastos comunes. Para ingresos que existen pero se gestionan aparte, como el alquiler de un piso.",
            ),
        ),
    ]
