# Generated by Django 5.2.1 on 2026-09-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0018_fuenteingreso_incluir_en_distribucion"),
    ]

    operations = [
        migrations.AddField(
            model_name="cierremensual",
            name="ahorro",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Importe que ese mes salió hacia fondos de ahorro.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cierremensual",
            name="libre",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Dinero que quedó libre ese mes, sin asignar a ningún fondo.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
