# Generated by Django 5.2.1 on 2026-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0019_cierremensual_ahorro_cierremensual_libre"),
    ]

    operations = [
        migrations.AddField(
            model_name="cierremensual",
            name="ingreso_previsto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Ingreso base presupuestado para ese mes (sin ajustes ni extras), tal y como estaba al cerrarlo. Es el "según el plan" con el que se compara lo que de verdad entró.',
                max_digits=12,
                null=True,
            ),
        ),
    ]
