# Generated by Django 5.2.1 on 2026-09-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0020_cierremensual_ingreso_previsto"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriagasto",
            name="computo",
            field=models.CharField(
                choices=[
                    ("resta", "Resta (cuenta como gasto)"),
                    ("suma", "Suma (cuenta como ingreso)"),
                    ("neutro", "Neutra (no cuenta ni como gasto ni como ingreso)"),
                ],
                default="resta",
                help_text="Cómo entran sus movimientos en los totales: restan (gasto), suman (ingreso) o son neutros (ni una cosa ni la otra).",
                max_length=10,
            ),
        ),
    ]
