# Generated by Django 5.2.1 on 2026-09-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_consultasql"),
        ("finanzas", "0022_computo_por_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPredefinidaDescartada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descartada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_descartadas",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría predefinida descartada",
                "verbose_name_plural": "Categorías predefinidas descartadas",
                "unique_together": {("hogar", "nombre")},
            },
        ),
    ]
