# Generated by Django 5.2.1 on 2026-09-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_consultasql"),
        ("finanzas", "0023_categoriapredefinidadescartada"),
    ]

    operations = [
        migrations.AddField(
            model_name="partidagasto",
            name="propiedad",
            field=models.ForeignKey(
                blank=True,
                help_text="Propiedad a la que pertenece este gasto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_imputados",
                to="finanzas.propiedad",
            ),
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Golf de Ana, Furgo del trabajo…", max_length=120
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("coche", "Coche"),
                            ("moto", "Moto"),
                            ("furgoneta", "Furgoneta"),
                            ("bici", "Bicicleta"),
                            ("otro", "Otro"),
                        ],
                        default="coche",
                        max_length=20,
                    ),
                ),
                ("marca_modelo", models.CharField(blank=True, max_length=120)),
                ("matricula", models.CharField(blank=True, max_length=20)),
                ("fecha_compra", models.DateField(blank=True, null=True)),
                (
                    "precio_compra",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lo que costó, para poder repartir su coste real de uso.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "valor_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valoración de mercado estimada a día de hoy.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("color", models.CharField(default="#2c5f7a", max_length=7)),
                ("notas", models.CharField(blank=True, max_length=300)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="partidagasto",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                help_text="Vehículo al que pertenece este gasto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_imputados",
                to="finanzas.vehiculo",
            ),
        ),
    ]
