# Generated by Django 5.2.1 on 2026-09-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0024_partidagasto_propiedad_vehiculo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuenteingreso",
            name="propiedad",
            field=models.ForeignKey(
                blank=True,
                help_text="Propiedad a la que pertenece este gasto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_imputados",
                to="finanzas.propiedad",
            ),
        ),
        migrations.AddField(
            model_name="fuenteingreso",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                help_text="Vehículo al que pertenece este gasto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_imputados",
                to="finanzas.vehiculo",
            ),
        ),
    ]
