# Generated by Django 5.2.1 on 2026-09-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0025_fuenteingreso_propiedad_fuenteingreso_vehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="partidagasto",
            name="bloque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fijo", "Gasto Fijo"),
                    ("anual", "Gasto Anual (provision)"),
                    ("variable", "Gasto Variable"),
                    ("discrecional", "Gasto Discrecional"),
                    ("ingreso", "Ingreso"),
                    ("traspaso", "Traspaso entre cuentas"),
                ],
                default="",
                help_text="Bloque al que pertenece cuando no hay categoría. Con categoría manda el bloque de la categoría.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="partidagasto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío si el presupuesto es del bloque entero y no de una categoría concreta.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partidas",
                to="finanzas.categoriagasto",
            ),
        ),
    ]
