# Generated by Django 5.2.1 on 2026-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0026_partidagasto_bloque_alter_partidagasto_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partidagasto",
            name="periodicidad",
            field=models.CharField(
                choices=[
                    ("mensual", "Mensual"),
                    ("bimensual", "Bimensual"),
                    ("trimestral", "Trimestral"),
                    ("semestral", "Semestral"),
                    ("anual", "Anual"),
                    ("bienal", "Cada 2 años"),
                    ("trienal", "Cada 3 años"),
                    ("quinquenal", "Cada 5 años"),
                ],
                default="mensual",
                help_text="Cada cuanto se paga este gasto",
                max_length=20,
            ),
        ),
    ]
