# Generated by Django 5.2.1 on 2026-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0027_alter_partidagasto_periodicidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="partidagasto",
            name="meses_personalizados",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Solo con periodicidad «Cada N meses»: cuántos meses dura o cada cuántos toca pagarlo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partidagasto",
            name="periodicidad",
            field=models.CharField(
                choices=[
                    ("mensual", "Mensual"),
                    ("bimensual", "Bimensual"),
                    ("trimestral", "Trimestral"),
                    ("semestral", "Semestral"),
                    ("anual", "Anual"),
                    ("bienal", "Cada 2 años"),
                    ("trienal", "Cada 3 años"),
                    ("quinquenal", "Cada 5 años"),
                    ("personalizada", "Cada N meses…"),
                ],
                default="mensual",
                help_text="Cada cuanto se paga este gasto",
                max_length=20,
            ),
        ),
    ]
