# Generated by Django 5.2.1 on 2026-09-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0028_partidagasto_meses_personalizados_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsobrefondo",
            name="bloque",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fijo", "Fijos"),
                    ("anual", "Fijos anuales"),
                    ("variable", "Variables"),
                    ("discrecional", "Discrecionales"),
                ],
                default="",
                help_text="Si se indica, el importe es lo que suma ese bloque del presupuesto, y se actualiza solo al añadir o cambiar gastos.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subsobrefondo",
            name="importe_manual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Importe mensual fijo si no sigue a un bloque ni a unas partidas.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
