# Generated by Django 5.2.1 on 2026-09-24 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_consultasql"),
        ("finanzas", "0029_subsobrefondo_bloque_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstudioVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "datos",
                    models.JSONField(
                        default=dict, help_text="Configuración completa del comparador."
                    ),
                ),
                (
                    "resumen",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cifras de cada opción al guardarlo, para la lista.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudios_vehiculo",
                        to="core.hogar",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estudios_vehiculo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudio de vehículo",
                "verbose_name_plural": "Estudios de vehículo",
                "ordering": ["-actualizado"],
            },
        ),
    ]
