# Generated by Django 5.2.1 on 2026-09-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0030_estudiovehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="partidagasto",
            name="plazos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Anuales pagados en varias veces: mes e importe de cada plazo.",
            ),
        ),
    ]
