# Generated by Django 5.2.1 on 2026-09-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0031_partidagasto_plazos"),
    ]

    operations = [
        migrations.AddField(
            model_name="partidagasto",
            name="anio_pago",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Solo gastos de más de un año: año en que toca (o tocó) un pago.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partidagasto",
            name="anios_dados_por_pagados",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Años en que esta partida se dio por pagada aunque no cuadre el importe.",
            ),
        ),
    ]
