# Generated by Django 5.2.1 on 2026-10-02 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0032_partidagasto_anio_pago_dados_por_pagados"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="alquilada",
            field=models.BooleanField(
                default=False, help_text="Está alquilada y da un ingreso."
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="intereses_hipoteca_anuales",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Intereses de la hipoteca pagados en el año (los da el banco).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="partida_irpf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finanzas.partidagasto",
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="pct_construccion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="% del valor catastral que es construcción (lo dice el recibo del IBI).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="propietario",
            field=models.ForeignKey(
                blank=True,
                help_text="Titular a efectos del IRPF. Vacío: a partes iguales entre los miembros del hogar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propiedades_propias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="reduccion_alquiler_pct",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Sin reducción (local, garaje, temporada, turístico)"),
                    (50, "50 % · vivienda habitual del inquilino (general)"),
                    (
                        60,
                        "60 % · contrato anterior a mayo de 2023 o vivienda rehabilitada",
                    ),
                    (
                        70,
                        "70 % · primer alquiler a joven de 18-35 años en zona tensionada",
                    ),
                    (
                        90,
                        "90 % · bajada de renta de al menos un 5 % en zona tensionada",
                    ),
                ],
                default=50,
                help_text="Reducción del rendimiento neto del alquiler en el IRPF.",
            ),
        ),
    ]
