# Generated by Django 5.2.1 on 2026-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0033_propiedad_alquiler"),
    ]

    operations = [
        migrations.AddField(
            model_name="partidagasto",
            name="ahorro_desde",
            field=models.DateField(
                blank=True,
                help_text="Gastos puntuales: mes desde el que se aparta dinero para él.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partidagasto",
            name="periodicidad",
            field=models.CharField(
                choices=[
                    ("mensual", "Mensual"),
                    ("bimensual", "Bimensual"),
                    ("trimestral", "Trimestral"),
                    ("semestral", "Semestral"),
                    ("anual", "Anual"),
                    ("bienal", "Cada 2 años"),
                    ("trienal", "Cada 3 años"),
                    ("quinquenal", "Cada 5 años"),
                    ("personalizada", "Cada N meses…"),
                    ("puntual", "Puntual (una sola vez)"),
                ],
                default="mensual",
                help_text="Cada cuanto se paga este gasto",
                max_length=20,
            ),
        ),
    ]
