# Generated by Django 5.2.1 on 2026-10-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0034_gasto_puntual"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="alquilada_desde",
            field=models.DateField(
                blank=True,
                help_text="Inicio del alquiler. Vacío: el mes del primer cobro imputado.",
                null=True,
            ),
        ),
    ]
