# Generated by Django 5.2.1 on 2026-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0035_propiedad_alquilada_desde"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="hipoteca_inicial",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Importe del préstamo hipotecario al comprar. Vacío o 0: sin hipoteca.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="simulacion_alquiler",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
