# Generated by Django 5.2.1 on 2026-10-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0035_propiedad_alquilada_desde"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrecioHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=20)),
                ("fecha", models.DateField()),
                ("cierre", models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                "ordering": ["ticker", "fecha"],
                "unique_together": {("ticker", "fecha")},
            },
        ),
    ]
