# Generated by Django 5.2.1 on 2026-10-05 20:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0037_precio_historico"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="tipo_marginal_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tipo marginal del IRPF. Vacío: se calcula con la nómina del titular.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="tipo_referencia_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rentabilidad alternativa del dinero (%). Vacío: 3 %.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="valor_construccion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor de la construcción (sin suelo) para la amortización del 3 %.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="gastos_venta_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("3.0"),
                help_text="% costes de venta: agencia, notaría, gestoría…",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="Hipoteca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="Hipoteca", max_length=100)),
                ("entidad", models.CharField(blank=True, max_length=100)),
                (
                    "capital_inicial",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fecha_firma", models.DateField()),
                (
                    "plazo_meses",
                    models.PositiveIntegerField(
                        help_text="Plazo total en meses (30 años = 360)."
                    ),
                ),
                (
                    "dia_cobro",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Día del mes en que se cobra. Vacío: el de la firma.",
                        null=True,
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("fijo", "Fijo"),
                            ("variable", "Variable"),
                            ("mixto", "Mixto"),
                        ],
                        default="fijo",
                        max_length=10,
                    ),
                ),
                (
                    "tipo_inicial_pct",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="TIN fijo, o el del tramo fijo inicial en variable y mixto.",
                        max_digits=6,
                    ),
                ),
                (
                    "meses_tramo_fijo",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Meses al tipo inicial antes de pasar a índice + diferencial.",
                        null=True,
                    ),
                ),
                (
                    "indice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("euribor_12m", "Euríbor a 12 meses"),
                            ("irph", "IRPH"),
                            ("otro", "Otro"),
                        ],
                        default="euribor_12m",
                        max_length=20,
                    ),
                ),
                (
                    "diferencial_pct",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "revision_meses",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Cada cuántos meses se revisa el tipo (6 o 12).",
                        null=True,
                    ),
                ),
                (
                    "saldo_conocido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("saldo_conocido_fecha", models.DateField(blank=True, null=True)),
                (
                    "cuota_conocida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cuota mensual en esa fecha. Vacío: se calcula con el plazo que queda.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "comision_pct_inicial",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "comision_meses_iniciales",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "comision_pct_despues",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("bonificaciones", models.JSONField(blank=True, default=list)),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "partida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finanzas.partidagasto",
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hipotecas",
                        to="finanzas.propiedad",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_firma", "pk"],
            },
        ),
        migrations.CreateModel(
            name="AmortizacionAnticipada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("importe", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "modo",
                    models.CharField(
                        choices=[
                            ("cuota", "Reducir cuota"),
                            ("plazo", "Reducir plazo"),
                        ],
                        default="plazo",
                        max_length=5,
                    ),
                ),
                (
                    "comision_pagada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="La comisión que se pagó. Vacío: se estima con la del préstamo.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "hipoteca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amortizaciones",
                        to="finanzas.hipoteca",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "pk"],
            },
        ),
        migrations.CreateModel(
            name="RevisionTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_desde", models.DateField()),
                ("tipo_pct", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "valor_indice_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Valor del índice usado en la revisión (informativo).",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "hipoteca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisiones",
                        to="finanzas.hipoteca",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_desde"],
                "unique_together": {("hipoteca", "fecha_desde")},
            },
        ),
    ]
