# Generated by Django 5.2.1 on 2025-05-15 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idioma",
                    models.CharField(
                        choices=[("es", "Español"), ("en", "Inglés")],
                        default="es",
                        max_length=10,
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("EUR", "€ Euro"),
                            ("USD", "$ Dólar"),
                            ("BTC", "₿ Bitcoin"),
                        ],
                        default="EUR",
                        max_length=5,
                    ),
                ),
                ("inflacion_referencia", models.FloatField(default=2.0)),
                ("porcentaje_max_endeudamiento", models.FloatField(default=30.0)),
                ("permitir_apis_externas", models.BooleanField(default=False)),
                ("mostrar_alertas", models.BooleanField(default=True)),
                ("recibir_emails", models.BooleanField(default=False)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
