# Generated by Django 5.2.1 on 2026-09-05 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile_tema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultaSQL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sql", models.TextField()),
                ("verbo", models.CharField(blank=True, default="", max_length=20)),
                (
                    "aplicado",
                    models.BooleanField(
                        default=False,
                        help_text="False = solo se probó (se deshizo); True = se aplicó de verdad.",
                    ),
                ),
                ("filas_afectadas", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("ejecutado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultas_sql",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta SQL",
                "verbose_name_plural": "Consultas SQL",
                "ordering": ["-ejecutado_en"],
            },
        ),
    ]
