# Generated by Django 5.2.1 on 2026-07-30 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_userprofile_rol_hogar_userprofile_hogar"),
        ("finanzas", "0008_merge_propiedad_historialpropiedad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractoBancario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_banco", models.CharField(blank=True, max_length=120)),
                ("archivo_nombre", models.CharField(blank=True, max_length=255)),
                ("fecha_importacion", models.DateTimeField(auto_now_add=True)),
                ("periodo_inicio", models.DateField(blank=True, null=True)),
                ("periodo_fin", models.DateField(blank=True, null=True)),
                ("num_movimientos", models.PositiveIntegerField(default=0)),
                (
                    "cuenta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extractos",
                        to="finanzas.cuentabancaria",
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractos",
                        to="core.hogar",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extractos_importados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracto bancario",
                "verbose_name_plural": "Extractos bancarios",
                "ordering": ["-fecha_importacion"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoBancario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("concepto", models.CharField(max_length=300)),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positivo = ingreso, negativo = gasto",
                        max_digits=12,
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estado_categorizacion",
                    models.CharField(
                        choices=[
                            ("sin_categorizar", "Sin categorizar"),
                            ("por_codigo", "Categorizado por código"),
                            ("por_ia", "Categorizado por IA"),
                            ("manual", "Categorizado manualmente"),
                        ],
                        default="sin_categorizar",
                        max_length=20,
                    ),
                ),
                (
                    "hash_dedupe",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_bancarios",
                        to="finanzas.categoriagasto",
                    ),
                ),
                (
                    "extracto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="extractos.extractobancario",
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_bancarios",
                        to="core.hogar",
                    ),
                ),
                (
                    "partida_conciliada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_conciliados",
                        to="finanzas.partidagasto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento bancario",
                "verbose_name_plural": "Movimientos bancarios",
                "ordering": ["-fecha", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hogar", "hash_dedupe"), name="uniq_mov_hogar_hash"
                    )
                ],
            },
        ),
    ]
