# Generated by Django 5.2.1 on 2026-07-31 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_rol_hogar_userprofile_hogar"),
        ("extractos", "0001_initial"),
        ("finanzas", "0008_merge_propiedad_historialpropiedad"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglaCategorizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patron",
                    models.CharField(
                        help_text="Texto que debe contener el concepto (se compara en minúsculas, sin distinguir acentos de mayúsculas).",
                        max_length=200,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[("manual", "Manual"), ("ia", "Asistente IA")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("veces_aplicada", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_categorizacion",
                        to="finanzas.categoriagasto",
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_categorizacion",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de categorización",
                "verbose_name_plural": "Reglas de categorización",
                "ordering": ["-creado_en"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hogar", "patron"), name="uniq_regla_cat_hogar_patron"
                    )
                ],
            },
        ),
    ]
