# Generated by Django 5.2.1 on 2026-08-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractos", "0002_reglacategorizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="comercio",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="movimientobancario",
            name="concepto_raw",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="movimientobancario",
            name="es_traspaso",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="movimientobancario",
            name="estado_categorizacion",
            field=models.CharField(
                choices=[
                    ("sin_categorizar", "Sin categorizar"),
                    ("por_codigo", "Categorizado por código"),
                    ("por_regla", "Categorizado por una regla aprendida"),
                    ("por_ia", "Categorizado por IA"),
                    ("manual", "Categorizado manualmente"),
                ],
                default="sin_categorizar",
                max_length=20,
            ),
        ),
    ]
