# Generated by Django 5.2.1 on 2026-09-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_consultasql"),
        ("extractos", "0005_rehash_movimientos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("color", models.CharField(default="#2d6a4f", max_length=7)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etiquetas",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="movimientobancario",
            name="etiquetas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cortes transversales (un viaje, una obra) que cruzan las categorías.",
                related_name="movimientos",
                to="extractos.etiqueta",
            ),
        ),
        migrations.AddConstraint(
            model_name="etiqueta",
            constraint=models.UniqueConstraint(
                fields=("hogar", "nombre"), name="uniq_etiqueta_hogar_nombre"
            ),
        ),
    ]
