# Generated by Django 5.2.1 on 2026-09-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractos", "0006_etiqueta_movimientobancario_etiquetas_and_more"),
        ("finanzas", "0023_categoriapredefinidadescartada"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="propiedad",
            field=models.ForeignKey(
                blank=True,
                help_text="Propiedad a la que pertenece este gasto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_imputados",
                to="finanzas.propiedad",
            ),
        ),
    ]
