# Generated by Django 5.2.1 on 2026-09-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractos", "0007_movimientobancario_propiedad"),
        ("finanzas", "0024_partidagasto_propiedad_vehiculo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                help_text="Vehículo al que pertenece este gasto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_imputados",
                to="finanzas.vehiculo",
            ),
        ),
    ]
