# Generated by Django 5.2.1 on 2026-09-15 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractos", "0008_movimientobancario_vehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="dividido_de",
            field=models.ForeignKey(
                blank=True,
                help_text="Si está relleno, esto es una parte de otro movimiento.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partes",
                to="extractos.movimientobancario",
            ),
        ),
        migrations.AddField(
            model_name="movimientobancario",
            name="orden_parte",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
