# Generated by Django 5.2.1 on 2026-09-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractos", "0009_movimientobancario_dividido_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="cubre",
            field=models.ForeignKey(
                blank=True,
                help_text="Pago al que este movimiento aporta dinero de la reserva.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coberturas",
                to="extractos.movimientobancario",
            ),
        ),
    ]
