# Generated by Django 5.2.1 on 2026-09-15 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_consultasql"),
        ("extractos", "0010_movimientobancario_cubre"),
        ("finanzas", "0028_partidagasto_meses_personalizados_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglaDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patron",
                    models.CharField(
                        help_text="Texto que debe contener el concepto (se compara en minúsculas, sin distinguir acentos de mayúsculas).",
                        max_length=200,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[("manual", "Manual"), ("ia", "Asistente IA")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("veces_aplicada", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_division",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de división",
                "verbose_name_plural": "Reglas de división",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ParteDeDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("proporcion", models.DecimalField(decimal_places=6, max_digits=9)),
                ("concepto", models.CharField(blank=True, default="", max_length=200)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partes_de_division",
                        to="finanzas.categoriagasto",
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        blank=True,
                        help_text="Propiedad a la que pertenece este gasto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_imputados",
                        to="finanzas.propiedad",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vehículo al que pertenece este gasto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_imputados",
                        to="finanzas.vehiculo",
                    ),
                ),
                (
                    "regla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partes",
                        to="extractos.regladivision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parte de una división",
                "verbose_name_plural": "Partes de una división",
                "ordering": ["orden"],
            },
        ),
        migrations.AddConstraint(
            model_name="regladivision",
            constraint=models.UniqueConstraint(
                fields=("hogar", "patron"), name="uniq_regla_div_hogar_patron"
            ),
        ),
    ]
