# Generated by Django 5.2.1 on 2026-09-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_consultasql"),
        ("extractos", "0011_regladivision_partededivision_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regladivision",
            options={
                "ordering": [
                    "patron",
                    models.OrderBy(models.F("desde"), descending=True, nulls_last=True),
                ],
                "verbose_name": "Regla de división",
                "verbose_name_plural": "Reglas de división",
            },
        ),
        migrations.RemoveConstraint(
            model_name="regladivision",
            name="uniq_regla_div_hogar_patron",
        ),
        migrations.AddField(
            model_name="regladivision",
            name="desde",
            field=models.DateField(
                blank=True,
                help_text="Desde qué fecha vale este reparto. En blanco, vale desde siempre.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="regladivision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("desde__isnull", False)),
                fields=("hogar", "patron", "desde"),
                name="uniq_regla_div_hogar_patron_desde",
            ),
        ),
        migrations.AddConstraint(
            model_name="regladivision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("desde__isnull", True)),
                fields=("hogar", "patron"),
                name="uniq_regla_div_hogar_patron_siempre",
            ),
        ),
    ]
