# Generated by Django 5.2.1 on 2026-09-16 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractos", "0012_alter_regladivision_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="manual",
            field=models.BooleanField(
                default=False,
                help_text="Apunte introducido a mano (un pago en efectivo), no importado.",
            ),
        ),
        migrations.AlterField(
            model_name="movimientobancario",
            name="extracto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="extractos.extractobancario",
            ),
        ),
    ]
