# Generated by Django 5.2.1 on 2026-09-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractos", "0013_movimientobancario_manual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="sin_reserva",
            field=models.BooleanField(
                default=False,
                help_text="Pago de un gasto no mensual que no salió de la reserva: cuenta entero en su mes.",
            ),
        ),
    ]
