# Generated by Django 5.2.1 on 2026-09-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractos", "0014_movimientobancario_sin_reserva"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="reembolsa",
            field=models.ForeignKey(
                blank=True,
                help_text="Gasto compartido del que este movimiento te devuelve una parte.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reembolsos",
                to="extractos.movimientobancario",
            ),
        ),
    ]
