# Generated by Django 5.2.1 on 2026-10-02 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_consultasql"),
        ("extractos", "0015_movimientobancario_reembolsa"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaldoReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=12)),
                ("nota", models.CharField(blank=True, max_length=200)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saldos_reserva",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saldo de la reserva",
                "verbose_name_plural": "Saldos de la reserva",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
    ]
