# Generated by Django 5.2.1 on 2026-07-29 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_userprofile_rol_hogar_userprofile_hogar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgenteIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "instrucciones",
                    models.TextField(
                        help_text="Instrucciones / system prompt para el modelo."
                    ),
                ),
                (
                    "proveedor_preferido",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("anthropic", "Claude (Anthropic)"),
                            ("openai", "ChatGPT (OpenAI)"),
                            ("gemini", "Gemini (Google)"),
                        ],
                        help_text="Si está vacío, se usa el proveedor activo del hogar.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("es_predeterminado", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agentes_ia_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agentes_ia",
                        to="core.hogar",
                    ),
                ),
            ],
            options={
                "ordering": ["-es_predeterminado", "nombre"],
                "unique_together": {("hogar", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proveedor_activo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("anthropic", "Claude (Anthropic)"),
                            ("openai", "ChatGPT (OpenAI)"),
                            ("gemini", "Gemini (Google)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "anthropic_api_key_cifrada",
                    models.BinaryField(blank=True, null=True),
                ),
                (
                    "anthropic_modelo",
                    models.CharField(default="claude-sonnet-5", max_length=60),
                ),
                ("openai_api_key_cifrada", models.BinaryField(blank=True, null=True)),
                ("openai_modelo", models.CharField(default="gpt-4o", max_length=60)),
                ("gemini_api_key_cifrada", models.BinaryField(blank=True, null=True)),
                (
                    "gemini_modelo",
                    models.CharField(default="gemini-2.0-flash", max_length=60),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hogar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_ia",
                        to="core.hogar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversacionIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True, default="Nueva conversación", max_length=150
                    ),
                ),
                ("contexto_financiero_cache", models.TextField(blank=True, default="")),
                ("contexto_generado_en", models.DateTimeField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "agente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversaciones",
                        to="asistente_ia.agenteia",
                    ),
                ),
                (
                    "hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones_ia",
                        to="core.hogar",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones_ia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-actualizado_en"],
            },
        ),
        migrations.CreateModel(
            name="MensajeIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("user", "Usuario"),
                            ("assistant", "Asistente"),
                            ("system", "Sistema"),
                        ],
                        max_length=10,
                    ),
                ),
                ("contenido", models.TextField()),
                ("proveedor", models.CharField(blank=True, default="", max_length=20)),
                ("modelo", models.CharField(blank=True, default="", max_length=60)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="asistente_ia.conversacionia",
                    ),
                ),
            ],
            options={
                "ordering": ["creado_en"],
            },
        ),
        migrations.CreateModel(
            name="AccionPropuestaIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_accion",
                    models.CharField(
                        choices=[
                            ("crear_gasto", "Crear partida de gasto"),
                            ("crear_categoria_gasto", "Crear categoría de gasto"),
                            ("crear_agente", "Crear agente IA"),
                            ("crear_ingreso", "Crear fuente de ingreso"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Datos propuestos por la IA, validados antes de aplicar."
                    ),
                ),
                ("resumen_legible", models.CharField(max_length=300)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("rechazada", "Rechazada"),
                            ("aplicada", "Aplicada"),
                            ("error", "Error al aplicar"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("detalle_error", models.TextField(blank=True, default="")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("resuelto_en", models.DateTimeField(blank=True, null=True)),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acciones_propuestas",
                        to="asistente_ia.conversacionia",
                    ),
                ),
                (
                    "mensaje_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acciones",
                        to="asistente_ia.mensajeia",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
