# Generated by Django 5.2.1 on 2026-07-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistente_ia", "0002_seed_agente_predeterminado"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenteia",
            name="allowed_tools",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Tipos de acciones de escritura que este agente puede proponer (p.ej. ["crear_gasto", "editar_gasto"]). Vacío = agente de solo lectura: las tools de lectura siempre están disponibles para cualquier agente, esto solo controla la escritura.',
            ),
        ),
        migrations.AddField(
            model_name="configuracionia",
            name="anthropic_api_key_hint",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="configuracionia",
            name="gemini_api_key_hint",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="configuracionia",
            name="openai_api_key_hint",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="accionpropuestaia",
            name="tipo_accion",
            field=models.CharField(
                choices=[
                    ("crear_gasto", "Crear partida de gasto"),
                    ("editar_gasto", "Editar partida de gasto"),
                    ("crear_categoria_gasto", "Crear categoría de gasto"),
                    ("crear_agente", "Crear agente IA"),
                    ("crear_ingreso", "Crear fuente de ingreso"),
                    ("editar_ingreso", "Editar fuente de ingreso"),
                ],
                max_length=40,
            ),
        ),
    ]
