# Generated by Django 5.2.1 on 2026-07-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistente_ia", "0005_agentes_categorizar_movimientos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accionpropuestaia",
            name="tipo_accion",
            field=models.CharField(
                choices=[
                    ("crear_gasto", "Crear partida de gasto"),
                    ("editar_gasto", "Editar partida de gasto"),
                    ("crear_categoria_gasto", "Crear categoría de gasto"),
                    ("crear_agente", "Crear agente IA"),
                    ("crear_ingreso", "Crear fuente de ingreso"),
                    ("editar_ingreso", "Editar fuente de ingreso"),
                    ("categorizar_movimientos", "Categorizar movimientos bancarios"),
                ],
                max_length=40,
            ),
        ),
    ]
